-- local reloader = function()
--   if SHOULD_RELOAD_TELESCOPE then
--     RELOAD "plenary"
--     RELOAD "telescope"
--     RELOAD "david.telescope.setup"
--     RELOAD "david.telescope.custom"
--   end
-- end
--
-- local actions = require "telescope.actions"
-- local action_state = require "telescope.actions.state"
-- local themes = require "telescope.themes"
--
-- local set_prompt_to_entry_value = function(prompt_bufnr)
--   local entry = action_state.get_selected_entry()
--   if not entry or not type(entry) == "table" then
--     return
--   end
--
--   action_state.get_current_picker(prompt_bufnr):reset_prompt(entry.ordinal)
-- end
--
-- local _ = pcall(require, "nvim-nonicons")
--
-- local M = {}
-- if not pcall(require, "copilot") then
--   return
-- end
--
-- local copilot = pcall(require, "copilot")
RELOAD "copilot"
-- require("copilot").setup({
--   panel = {
--     enabled = true,
--   }
-- }
-- )
-- require("copilot").setup{
--   panel = {
--     enabled = true,
--     auto_refresh = false,
--     keymap = {
--       jump_prev = "[[",
--       jump_next = "]]",
--       accept = "<CR>",
--       refresh = "gr",
--       open = "<M-CR>"
--     },
--     layout = {
--       position = "bottom", -- | top | left | right
--       ratio = 0.4
--     },
--   },
--   suggestion = {
--     enabled = true,
--     auto_trigger = false,
--     debounce = 75,
--     keymap = {
--       accept = "<M-l>",
--       accept_word = false,
--       accept_line = false,
--       next = "<M-]>",
--       prev = "<M-[>",
--       dismiss = "<C-]>",
--     },
--   },
--   filetypes = {
--     yaml = false,
--     markdown = false,
--     help = false,
--     gitcommit = false,
--     gitrebase = false,
--     hgcommit = false,
--     svn = false,
--     cvs = false,
--     ["."] = false,
--   },
--   copilot_node_command = 'node', -- Node.js version must be > 16.x
--   server_opts_overrides = {},
-- }


 -- require("copilot").setup({
 --        suggestion = {
 --          enabled = true,
 --          auto_trigger = true,
 --          debounce = 75,
 --        },
 --        filetypes = {
 --          python = true,
 --          rust = true,
 --          ["*"] = false,
 --        },
 --      })
